server.port=8081
spring.application.name=book-service

# Switch between "in-memory" and "jpa"
spring.profiles.active=jpa

# H2 console (only active with jpa profile)
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:bookdb
spring.jpa.hibernate.ddl-auto=create-drop